# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SecretVault' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SecretVault
    pod 'GCDWebServer'
    pod 'NVActivityIndicatorView'
    pod 'GoogleAPIClientForREST/Drive'
    pod 'GoogleSignIn'
    pod 'SwiftyDropbox'
    pod 'RealmSwift'
    pod 'Firebase', '~> 6.7.0'
    pod 'ADALiOS'
    pod 'OneDriveSDK'
    pod 'GTMOAuth2'
    pod 'Alamofire'
    pod 'Google-Mobile-Ads-SDK', '~> 7.49.0'
    pod 'FGRoute'
    pod 'SSZipArchive'
    #pod "UnrarKit"

pod 'SCSafariPageController'

pod 'DeviceKit'
  # Progress
  pod 'PKHUD'
  pod 'BRYXBanner'
  
  
  # Network
  pod 'ReachabilitySwift'

  pod 'AlamofireNetworkActivityIndicator'
  pod 'SwiftyJSON'
  # Image
  pod 'Kingfisher'
  
  # Local Storage
   
  # UI
  pod 'SnapKit'



end
